"""Constants for claim evidence timeline/reporting."""

EVIDENCE_EVENT_TYPES = (
    "EMAIL_SENT",
    "EMAIL_RECEIVED",
    "ATTACHMENT_ADDED",
    "ESTIMATE_UPLOADED",
    "ESTIMATE_REVISED",
    "INSPECTION_SCHEDULED",
    "INSPECTION_COMPLETED",
    "DOC_SUBMITTED_TO_CARRIER",
    "COVERAGE_DETERMINATION",
    "PAYMENT_ISSUED",
    "REQUEST_FOR_INFO",
    "RECORDED_STATEMENT_REQUESTED",
    "MEDIATION_APPRAISAL",
    "CLAIM_CLOSED",
    "NOTE",
)

EVENT_TYPE_PRIORITY = {
    "EMAIL_RECEIVED": 10,
    "EMAIL_SENT": 20,
    "ATTACHMENT_ADDED": 30,
    "ESTIMATE_UPLOADED": 40,
    "ESTIMATE_REVISED": 45,
    "INSPECTION_SCHEDULED": 50,
    "INSPECTION_COMPLETED": 55,
    "DOC_SUBMITTED_TO_CARRIER": 60,
    "REQUEST_FOR_INFO": 65,
    "RECORDED_STATEMENT_REQUESTED": 70,
    "MEDIATION_APPRAISAL": 75,
    "COVERAGE_DETERMINATION": 80,
    "PAYMENT_ISSUED": 90,
    "CLAIM_CLOSED": 100,
    "NOTE": 110,
}

AUTO_INGEST_THRESHOLD = 70
REVIEW_QUEUE_THRESHOLD = 45

DEFAULT_REPORT_TEMPLATE_CLIENT = "client_report_v1"
DEFAULT_REPORT_TEMPLATE_CARRIER = "carrier_packet_v1"

REPORT_TYPES = ("client_report", "carrier_packet")
