import { BattlePassTier, LeaderboardEntry, Mission } from './types';

export const tiers: BattlePassTier[] = [
  {
    id: 'tier-1',
    level: 1,
    xpRequired: 0,
    reward: {
      id: 'bp-recruit',
      name: 'Recruit Sigil',
      description: 'Operator onboarding complete.',
      iconUrl: '/icons/tier_recruit.png',
      rarity: 'common',
    },
  },
  {
    id: 'tier-2',
    level: 2,
    xpRequired: 450,
    reward: {
      id: 'bp-agent',
      name: 'Agent Crest',
      description: 'Mission-ready badge for active reps.',
      iconUrl: '/icons/tier_agent.png',
      rarity: 'uncommon',
    },
  },
  {
    id: 'tier-3',
    level: 3,
    xpRequired: 1200,
    reward: {
      id: 'bp-veteran',
      name: 'Veteran Mark',
      description: 'Sustained outcomes in the field.',
      iconUrl: '/icons/tier_veteran.png',
      rarity: 'rare',
    },
  },
  {
    id: 'tier-4',
    level: 4,
    xpRequired: 2200,
    reward: {
      id: 'bp-elite',
      name: 'Elite Emblem',
      description: 'High consistency under pressure.',
      iconUrl: '/icons/tier_elite.png',
      rarity: 'epic',
    },
  },
  {
    id: 'tier-5',
    level: 5,
    xpRequired: 3600,
    reward: {
      id: 'bp-commander',
      name: 'Commander Plate',
      description: 'Controls the board and closes hard.',
      iconUrl: '/icons/tier_commander.png',
      rarity: 'legendary',
    },
  },
  {
    id: 'tier-6',
    level: 6,
    xpRequired: 5400,
    reward: {
      id: 'bp-apex',
      name: 'Apex Relic',
      description: 'Mythic season capstone.',
      iconUrl: '/icons/tier_apex.png',
      rarity: 'mythic',
    },
  },
];

export const missionsSeed: Mission[] = [
  {
    id: 'd1',
    title: 'Knock 25 Doors',
    description: 'Complete 25 qualified doors today.',
    rarity: 'common',
    type: 'daily',
    progress: 18,
    target: 25,
    xp: 120,
  },
  {
    id: 'd2',
    title: 'Book 2 Inspections',
    description: 'Set 2 first-call inspections.',
    rarity: 'uncommon',
    type: 'daily',
    progress: 1,
    target: 2,
    xp: 180,
  },
  {
    id: 'd3',
    title: 'Upload Claim Notes',
    description: 'Post complete notes for 3 claims.',
    rarity: 'rare',
    type: 'daily',
    progress: 2,
    target: 3,
    xp: 220,
  },
  {
    id: 'w1',
    title: '5 Signed Contracts',
    description: 'Get 5 contracts signed this week.',
    rarity: 'epic',
    type: 'weekly',
    progress: 3,
    target: 5,
    xp: 500,
  },
  {
    id: 'w2',
    title: 'Hit 15K Team XP',
    description: 'Contribute 15K XP to your territory.',
    rarity: 'legendary',
    type: 'weekly',
    progress: 10200,
    target: 15000,
    xp: 650,
  },
  {
    id: 's1',
    title: 'Season Push: 20 Contracts',
    description: 'Close 20 contracts before season end.',
    rarity: 'mythic',
    type: 'seasonal',
    progress: 12,
    target: 20,
    xp: 1200,
  },
  {
    id: 's2',
    title: '90% Follow-up SLA',
    description: 'Maintain 90% follow-up completion.',
    rarity: 'epic',
    type: 'seasonal',
    progress: 84,
    target: 90,
    xp: 900,
  },
];

export const leaderboardSeed: LeaderboardEntry[] = [
  {
    id: 'u1',
    name: 'J. Rivera',
    title: 'Field Commander',
    avatarUrl: '/icons/tier_field_marshal.png',
    totalXp: 8120,
    tierLevel: 6,
    missionsCompleted: 58,
    rewardsClaimed: 12,
    streakDaily: 22,
    streakWeekly: 8,
    change: 3,
  },
  {
    id: 'u2',
    name: 'A. Cooper',
    title: 'Elite Agent',
    avatarUrl: '/icons/tier_elite.png',
    totalXp: 7650,
    tierLevel: 5,
    missionsCompleted: 53,
    rewardsClaimed: 10,
    streakDaily: 19,
    streakWeekly: 6,
    change: -1,
  },
  {
    id: 'u3',
    name: 'M. James',
    title: 'Tactical Lead',
    avatarUrl: '/icons/tier_veteran.png',
    totalXp: 7215,
    tierLevel: 5,
    missionsCompleted: 49,
    rewardsClaimed: 10,
    streakDaily: 17,
    streakWeekly: 6,
    change: 1,
  },
  {
    id: 'u4',
    name: 'K. Shah',
    title: 'Field Ops',
    avatarUrl: '/icons/tier_agent.png',
    totalXp: 6680,
    tierLevel: 4,
    missionsCompleted: 44,
    rewardsClaimed: 8,
    streakDaily: 16,
    streakWeekly: 5,
    change: 0,
  },
  {
    id: 'u5',
    name: 'S. Moore',
    title: 'Recon Specialist',
    avatarUrl: '/icons/tier_recruit.png',
    totalXp: 6320,
    tierLevel: 4,
    missionsCompleted: 40,
    rewardsClaimed: 8,
    streakDaily: 14,
    streakWeekly: 4,
    change: 2,
  },
];
